# Generated by Django 3.1.4 on 2021-01-11 13:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 11, 13, 18, 55, 650597, tzinfo=utc)),
        ),
    ]
