# Generated by Django 3.1.4 on 2021-01-13 11:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210111_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 13, 11, 49, 10, 317845, tzinfo=utc)),
        ),
    ]
